export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

export const API_LIMITS = {
  DEFAULT_MAX_REQUESTS: 1000,
  MAX_BATCH_SIZE: 100,
  MIN_BATCH_SIZE: 1,
} as const;

export const TIME_CONSTANTS = {
  SECONDS_PER_HOUR: 3600,
  RATE_LIMIT_RESET_HOURS: 1,
} as const;
